/** LC-12 — Legal persistence SQL schema manifest (parity with LC-11 row contracts) */

export const LEGAL_PERSISTENCE_MIGRATION_FILE =
  'supabase/migrations/20260721044500_legal_center_persistence_foundation.sql';

export const LEGAL_PERSISTENCE_TABLES = [
  'legal_templates',
  'legal_template_versions',
  'legal_template_assets',
  'legal_document_instances',
  'legal_w9_requests',
  'legal_document_submissions',
  'legal_audit_events',
] as const;

export type LegalPersistenceTableName = (typeof LEGAL_PERSISTENCE_TABLES)[number];

/** Maps LC-11 row property → SQL column (when names differ). */
export const LEGAL_PERSISTENCE_ROW_SQL_COLUMN_MAP = {
  legal_templates: {
    id: 'id',
    business_id: 'business_id',
    template_code: 'template_code',
    category: 'category',
    official_name: 'official_name',
    current_published_version_id: 'current_published_version_id',
    status: 'status',
    is_policy: 'is_policy',
    requires_countersign: 'requires_countersign',
    counsel_review_required: 'counsel_review_required',
    signature_plan_default: 'signature_plan_default',
    field_schema_default: 'field_schema_default',
    created_at: 'created_at',
    updated_at: 'updated_at',
    row_version: 'row_version',
  },
  legal_template_versions: {
    id: 'id',
    business_id: 'business_id',
    template_id: 'template_row_id',
    template_business_id: 'template_business_id',
    semver: 'semver',
    content_hash: 'content_hash',
    published_at: 'published_at',
    published_by_staff_id: 'published_by_staff_id',
    effective_from: 'effective_from',
    retired_at: 'retired_at',
    locale_bodies: 'locale_bodies',
    row_version: 'row_version',
  },
  legal_template_assets: {
    id: 'id',
    template_version_id: 'template_version_row_id',
    template_business_id: 'template_business_id',
    template_version_business_id: 'template_version_business_id',
    asset_key: 'asset_key',
    filename: 'filename',
    mime_type: 'mime_type',
    kind: 'kind',
    category: 'category',
    availability: 'availability',
    object_key: 'object_key',
    shared_across_portals: 'shared_across_portals',
    allowed_portals: 'allowed_portals',
    is_public_library_document: 'is_public_library_document',
    row_version: 'row_version',
  },
  legal_document_instances: {
    id: 'id',
    business_id: 'business_id',
    template_id: 'template_business_id',
    template_version_id: 'template_version_business_id',
    category: 'category',
    title: 'title',
    recipient_type: 'recipient_type',
    recipient_id: 'recipient_id',
    recipient_display_name: 'recipient_display_name',
    recipient_email: 'recipient_email',
    owner_type: 'owner_type',
    owner_id: 'owner_id',
    issued_by: 'issued_by',
    assigned_by: 'assigned_by',
    status: 'status',
    instance_version: 'instance_version',
    source: 'source',
    signature_requirement: 'signature_requirement',
    metadata: 'metadata',
    expires_at: 'expires_at',
    sent_at: 'sent_at',
    viewed_at: 'viewed_at',
    signed_at: 'signed_at',
    rejected_at: 'rejected_at',
    cancelled_at: 'cancelled_at',
    expired_at: 'expired_at',
    created_at: 'created_at',
    updated_at: 'updated_at',
    row_version: 'row_version',
  },
  legal_w9_requests: {
    id: 'id',
    business_id: 'business_id',
    document_instance_id: 'document_instance_row_id',
    document_instance_business_id: 'document_instance_business_id',
    template_id: 'template_business_id',
    template_version_id: 'template_version_business_id',
    recipient_type: 'recipient_type',
    recipient_id: 'recipient_id',
    recipient_display_name: 'recipient_display_name',
    recipient_email: 'recipient_email',
    requested_by_actor_id: 'requested_by_actor_id',
    requested_by_display_name: 'requested_by_display_name',
    requested_by_role: 'requested_by_role',
    status: 'status',
    review_status: 'review_status',
    submission_id: 'submission_row_id',
    submission_business_id: 'submission_business_id',
    requested_at: 'requested_at',
    updated_at: 'updated_at',
    due_at: 'due_at',
    viewed_at: 'viewed_at',
    completed_at: 'completed_at',
    metadata: 'metadata',
    row_version: 'row_version',
  },
  legal_document_submissions: {
    id: 'id',
    business_id: 'business_id',
    document_instance_id: 'document_instance_row_id',
    document_instance_business_id: 'document_instance_business_id',
    workflow_id: 'workflow_row_id',
    workflow_business_id: 'workflow_business_id',
    template_id: 'template_business_id',
    template_version_id: 'template_version_business_id',
    storage_key: 'storage_key',
    filename: 'filename',
    mime_type: 'mime_type',
    size_bytes: 'size_bytes',
    checksum: 'checksum',
    content_reference: 'content_reference',
    submitted_by_actor_id: 'submitted_by_actor_id',
    submitted_by_display_name: 'submitted_by_display_name',
    submitted_by_portal: 'submitted_by_portal',
    submitted_by_role: 'submitted_by_role',
    status: 'status',
    metadata: 'metadata',
    replaces_submission_id: 'replaces_submission_row_id',
    replaced_by_submission_id: 'replaced_by_submission_row_id',
    deleted_at: 'deleted_at',
    deleted_by_actor_id: 'deleted_by_actor_id',
    delete_reason_code: 'delete_reason_code',
    recipient_type: 'recipient_type',
    recipient_id: 'recipient_id',
    created_at: 'created_at',
    submitted_at: 'submitted_at',
    updated_at: 'updated_at',
    row_version: 'row_version',
  },
  legal_audit_events: {
    id: 'id',
    business_id: 'business_id',
    sequence: 'sequence',
    occurred_at: 'occurred_at',
    actor_type: 'actor_type',
    actor_id: 'actor_id',
    actor_role: 'actor_role',
    actor_portal: 'actor_portal',
    actor_display_name: 'actor_display_name',
    action: 'action',
    entity_type: 'entity_type',
    entity_id: 'entity_id',
    related_entity_ids: 'related_entity_ids',
    previous_state: 'previous_state',
    next_state: 'next_state',
    outcome: 'outcome',
    reason_code: 'reason_code',
    correlation_id: 'correlation_id',
    request_id: 'request_id',
    metadata: 'metadata',
  },
} as const satisfies Record<LegalPersistenceTableName, Readonly<Record<string, string>>>;

export const LEGAL_PERSISTENCE_ACTIVE_W9_STATUSES = [
  'requested',
  'available',
  'viewed',
  'awaiting_upload',
  'submitted',
] as const;

export const LEGAL_PERSISTENCE_TERMINAL_W9_STATUSES = [
  'accepted',
  'rejected',
  'expired',
  'cancelled',
] as const;

export const LEGAL_PERSISTENCE_SUBMISSION_MAX_BYTES = 20 * 1024 * 1024;
