/** Legal lab fixtures — TICKET-V2-LEGAL-IN-MEMORY-SERVICE-001 */

import type {
  AcceptanceRecord,
  AuditEvent,
  ComplianceProfile,
  IntroductionRecord,
  LegalDocument,
  LegalNotification,
  LegalProfile,
  SignaturePackage,
  SignatureRecord,
  SigningSession,
  TaxProfile,
} from '../contracts/legal-entities';
import type { LegalRestriction } from '../contracts/legal-enums';
import type { InMemoryLegalStoreState } from './in-memory-legal-store';

export const LEGAL_FIXTURE_PROFILE_IDS = Object.freeze({
  artistGreen: 'LP-ART-GREEN-001',
  artistYellow: 'LP-ART-YELLOW-001',
  providerRed: 'LP-PRO-RED-001',
  client: 'LP-CLI-001',
  externalSigner: 'LP-EXT-001',
});

export const LEGAL_FIXTURE_PACKAGE_IDS = Object.freeze({
  externalPackage: 'PKG-EXT-001',
  yellowPackage: 'PKG-YELLOW-001',
});

export const LEGAL_FIXTURE_INTRODUCTION_IDS = Object.freeze({
  canonical: 'INTRO-2026-000421',
});

export const LEGAL_FIXTURE_EXPEDIENTE = Object.freeze({
  artistGreen: LEGAL_FIXTURE_PROFILE_IDS.artistGreen,
  artistYellow: LEGAL_FIXTURE_PROFILE_IDS.artistYellow,
  providerRed: LEGAL_FIXTURE_PROFILE_IDS.providerRed,
  client: LEGAL_FIXTURE_PROFILE_IDS.client,
  externalSigner: LEGAL_FIXTURE_PROFILE_IDS.externalSigner,
});

const STAFF_ID = 'STF-0001';
const NOW = '2026-07-20T21:00:00.000Z';

const sharedDocumentPermissions = Object.freeze({
  read: Object.freeze(['owner', 'staff_manager'] as const),
  download: Object.freeze(['owner', 'staff_manager'] as const),
  sign: Object.freeze(['owner'] as const),
});

const artistGreenProfile: LegalProfile = Object.freeze({
  legalProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistGreen,
  subjectType: 'artist',
  userId: 'usr-art-green-001',
  mdjbId: 'MDJB-ART1-0001-A',
  legalName: 'Gerardo A Valle',
  primaryEmail: 'artist.green@lab.mdj',
  aggregateStatus: 'GREEN',
  statusComputedAt: NOW,
  statusItems: Object.freeze([
    Object.freeze({
      itemCode: 'partner_agreement',
      itemState: 'green',
      labelKey: 'legal.status.partner_agreement',
    }),
    Object.freeze({
      itemCode: 'w9',
      itemState: 'green',
      labelKey: 'legal.status.w9',
    }),
    Object.freeze({
      itemCode: 'insurance',
      itemState: 'green',
      labelKey: 'legal.status.insurance',
      expiresAt: '2027-06-01T00:00:00.000Z',
    }),
    Object.freeze({
      itemCode: 'policy_bundle',
      itemState: 'green',
      labelKey: 'legal.status.policy_bundle',
    }),
  ]),
  restrictions: Object.freeze([]),
  documentIds: Object.freeze([
    'DOC-GREEN-LGL-001',
    'DOC-GREEN-LGL-002',
    'DOC-GREEN-LGL-003',
    'DOC-GREEN-CTR-001',
    'DOC-GREEN-SPC-001',
    'DOC-GREEN-SPC-002',
  ]),
  taxProfileId: 'TAX-ART-GREEN-001',
  complianceProfileId: 'CMP-ART-GREEN-001',
  introductionIds: Object.freeze([LEGAL_FIXTURE_INTRODUCTION_IDS.canonical]),
  activePackageIds: Object.freeze([]),
  createdAt: '2026-01-10T12:00:00.000Z',
  updatedAt: NOW,
});

const artistYellowProfile: LegalProfile = Object.freeze({
  legalProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistYellow,
  subjectType: 'artist',
  userId: 'usr-art-yellow-001',
  mdjbId: 'MDJB-ART2-0002-A',
  legalName: 'DJ Nova Lab',
  primaryEmail: 'artist.yellow@lab.mdj',
  aggregateStatus: 'YELLOW',
  statusComputedAt: NOW,
  statusItems: Object.freeze([
    Object.freeze({
      itemCode: 'partner_agreement',
      itemState: 'green',
      labelKey: 'legal.status.partner_agreement',
    }),
    Object.freeze({
      itemCode: 'w9',
      itemState: 'green',
      labelKey: 'legal.status.w9',
    }),
    Object.freeze({
      itemCode: 'insurance',
      itemState: 'yellow',
      labelKey: 'legal.status.insurance',
      expiresAt: '2026-08-10T00:00:00.000Z',
    }),
    Object.freeze({
      itemCode: 'policy_bundle',
      itemState: 'green',
      labelKey: 'legal.status.policy_bundle',
    }),
  ]),
  restrictions: Object.freeze([]),
  documentIds: Object.freeze([
    'DOC-YELLOW-LGL-001',
    'DOC-YELLOW-LGL-002',
    'DOC-YELLOW-LGL-003',
    'DOC-YELLOW-CTR-001',
    'DOC-YELLOW-SPC-001',
    'DOC-YELLOW-SPC-002',
  ]),
  taxProfileId: 'TAX-ART-YELLOW-001',
  complianceProfileId: 'CMP-ART-YELLOW-001',
  introductionIds: Object.freeze([]),
  activePackageIds: Object.freeze([LEGAL_FIXTURE_PACKAGE_IDS.yellowPackage]),
  createdAt: '2026-03-01T12:00:00.000Z',
  updatedAt: NOW,
});

const providerRedProfile: LegalProfile = Object.freeze({
  legalProfileId: LEGAL_FIXTURE_PROFILE_IDS.providerRed,
  subjectType: 'vendor',
  userId: 'usr-pro-red-001',
  mdjbId: 'MDJB-VEN1-0003-S',
  legalName: 'Blocked Vendor Services LLC',
  primaryEmail: 'vendor.red@lab.mdj',
  aggregateStatus: 'RED',
  statusComputedAt: NOW,
  statusItems: Object.freeze([
    Object.freeze({
      itemCode: 'partner_agreement',
      itemState: 'red',
      labelKey: 'legal.status.partner_agreement',
      expiresAt: '2026-06-01T00:00:00.000Z',
    }),
    Object.freeze({
      itemCode: 'w9',
      itemState: 'red',
      labelKey: 'legal.status.w9',
    }),
    Object.freeze({
      itemCode: 'insurance',
      itemState: 'red',
      labelKey: 'legal.status.insurance',
      expiresAt: '2026-05-15T00:00:00.000Z',
    }),
    Object.freeze({
      itemCode: 'anti_bypass',
      itemState: 'red',
      labelKey: 'legal.status.anti_bypass',
    }),
  ]),
  restrictions: Object.freeze([
    'no_matching',
    'no_payout',
    'no_booking_accept',
    'no_corporate',
  ] as readonly LegalRestriction[]),
  documentIds: Object.freeze([
    'DOC-RED-LGL-001',
    'DOC-RED-LGL-002',
    'DOC-RED-CTR-001',
    'DOC-RED-SPC-002',
  ]),
  taxProfileId: 'TAX-PRO-RED-001',
  complianceProfileId: 'CMP-PRO-RED-001',
  introductionIds: Object.freeze([]),
  activePackageIds: Object.freeze([]),
  createdAt: '2026-02-01T12:00:00.000Z',
  updatedAt: NOW,
});

const clientProfile: LegalProfile = Object.freeze({
  legalProfileId: LEGAL_FIXTURE_PROFILE_IDS.client,
  subjectType: 'client',
  userId: 'usr-cli-001',
  mdjbId: 'MDJB-CLI1-0001-C',
  legalName: 'Sunset Events LLC',
  primaryEmail: 'client@lab.mdj',
  aggregateStatus: 'GREEN',
  statusComputedAt: NOW,
  statusItems: Object.freeze([
    Object.freeze({
      itemCode: 'service_agreement',
      itemState: 'green',
      labelKey: 'legal.status.service_agreement',
    }),
    Object.freeze({
      itemCode: 'terms_of_service',
      itemState: 'green',
      labelKey: 'legal.status.terms_of_service',
    }),
  ]),
  restrictions: Object.freeze([]),
  documentIds: Object.freeze(['DOC-CLI-CTR-002', 'DOC-CLI-LGL-001']),
  complianceProfileId: 'CMP-CLI-001',
  introductionIds: Object.freeze([]),
  activePackageIds: Object.freeze([]),
  createdAt: '2026-04-01T12:00:00.000Z',
  updatedAt: NOW,
});

const externalSignerProfile: LegalProfile = Object.freeze({
  legalProfileId: LEGAL_FIXTURE_PROFILE_IDS.externalSigner,
  subjectType: 'external',
  legalName: 'External Signer Lab',
  primaryEmail: 'external.signer@lab.mdj',
  aggregateStatus: 'YELLOW',
  statusComputedAt: NOW,
  statusItems: Object.freeze([
    Object.freeze({
      itemCode: 'pending_package',
      itemState: 'yellow',
      labelKey: 'legal.status.pending_package',
    }),
  ]),
  restrictions: Object.freeze([]),
  documentIds: Object.freeze([]),
  activePackageIds: Object.freeze([LEGAL_FIXTURE_PACKAGE_IDS.externalPackage]),
  createdAt: '2026-07-01T12:00:00.000Z',
  updatedAt: NOW,
});

function createDocuments(): LegalDocument[] {
  return [
    Object.freeze({
      documentId: 'DOC-GREEN-LGL-001',
      templateCode: 'LGL-001',
      category: 'LGL',
      templateVersionId: 'TV-LGL-001-1',
      versionLabel: '2.1',
      ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistGreen,
      signerProfileIds: Object.freeze([LEGAL_FIXTURE_PROFILE_IDS.artistGreen]),
      lifecycleStatus: 'COMPLETED',
      signedAt: '2026-01-10T12:30:00.000Z',
      permissions: sharedDocumentPermissions,
      locale: 'en',
      createdAt: '2026-01-10T12:00:00.000Z',
    }),
    Object.freeze({
      documentId: 'DOC-GREEN-LGL-002',
      templateCode: 'LGL-002',
      category: 'LGL',
      templateVersionId: 'TV-LGL-002-1',
      versionLabel: '1.4',
      ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistGreen,
      signerProfileIds: Object.freeze([LEGAL_FIXTURE_PROFILE_IDS.artistGreen]),
      lifecycleStatus: 'COMPLETED',
      signedAt: '2026-01-10T12:35:00.000Z',
      permissions: sharedDocumentPermissions,
      locale: 'en',
      createdAt: '2026-01-10T12:00:00.000Z',
    }),
    Object.freeze({
      documentId: 'DOC-GREEN-LGL-003',
      templateCode: 'LGL-003',
      category: 'LGL',
      templateVersionId: 'TV-LGL-003-1',
      versionLabel: '1.0',
      ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistGreen,
      signerProfileIds: Object.freeze([LEGAL_FIXTURE_PROFILE_IDS.artistGreen]),
      lifecycleStatus: 'COMPLETED',
      signedAt: '2026-01-10T12:40:00.000Z',
      permissions: sharedDocumentPermissions,
      locale: 'en',
      createdAt: '2026-01-10T12:00:00.000Z',
    }),
    Object.freeze({
      documentId: 'DOC-GREEN-CTR-001',
      templateCode: 'CTR-001',
      category: 'CTR',
      templateVersionId: 'TV-CTR-001-1',
      versionLabel: '1.0',
      ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistGreen,
      signerProfileIds: Object.freeze([LEGAL_FIXTURE_PROFILE_IDS.artistGreen]),
      lifecycleStatus: 'COMPLETED',
      signedAt: '2026-01-15T18:00:00.000Z',
      finalArtifactId: 'ART-GREEN-CTR-001',
      permissions: sharedDocumentPermissions,
      locale: 'en',
      createdAt: '2026-01-15T17:00:00.000Z',
    }),
    Object.freeze({
      documentId: 'DOC-GREEN-SPC-001',
      templateCode: 'SPC-001',
      category: 'SPC',
      templateVersionId: 'TV-SPC-001-1',
      versionLabel: '1.0',
      ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistGreen,
      signerProfileIds: Object.freeze([LEGAL_FIXTURE_PROFILE_IDS.artistGreen]),
      lifecycleStatus: 'COMPLETED',
      signedAt: '2026-01-16T18:00:00.000Z',
      finalArtifactId: 'ART-GREEN-W9-001',
      permissions: sharedDocumentPermissions,
      locale: 'en',
      createdAt: '2026-01-16T17:00:00.000Z',
    }),
    Object.freeze({
      documentId: 'DOC-GREEN-SPC-002',
      templateCode: 'SPC-002',
      category: 'SPC',
      templateVersionId: 'TV-SPC-002-1',
      versionLabel: '1.0',
      ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistGreen,
      signerProfileIds: Object.freeze([LEGAL_FIXTURE_PROFILE_IDS.artistGreen]),
      lifecycleStatus: 'COMPLETED',
      signedAt: '2026-02-01T18:00:00.000Z',
      expiresAt: '2027-06-01T00:00:00.000Z',
      finalArtifactId: 'ART-GREEN-INS-001',
      permissions: sharedDocumentPermissions,
      locale: 'en',
      createdAt: '2026-02-01T17:00:00.000Z',
    }),
    Object.freeze({
      documentId: 'DOC-YELLOW-LGL-001',
      templateCode: 'LGL-001',
      category: 'LGL',
      templateVersionId: 'TV-LGL-001-1',
      versionLabel: '2.1',
      ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistYellow,
      signerProfileIds: Object.freeze([LEGAL_FIXTURE_PROFILE_IDS.artistYellow]),
      lifecycleStatus: 'COMPLETED',
      signedAt: '2026-03-01T12:30:00.000Z',
      permissions: sharedDocumentPermissions,
      locale: 'en',
      createdAt: '2026-03-01T12:00:00.000Z',
    }),
    Object.freeze({
      documentId: 'DOC-YELLOW-LGL-002',
      templateCode: 'LGL-002',
      category: 'LGL',
      templateVersionId: 'TV-LGL-002-1',
      versionLabel: '1.4',
      ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistYellow,
      signerProfileIds: Object.freeze([LEGAL_FIXTURE_PROFILE_IDS.artistYellow]),
      lifecycleStatus: 'COMPLETED',
      signedAt: '2026-03-01T12:35:00.000Z',
      permissions: sharedDocumentPermissions,
      locale: 'en',
      createdAt: '2026-03-01T12:00:00.000Z',
    }),
    Object.freeze({
      documentId: 'DOC-YELLOW-LGL-003',
      templateCode: 'LGL-003',
      category: 'LGL',
      templateVersionId: 'TV-LGL-003-1',
      versionLabel: '1.0',
      ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistYellow,
      signerProfileIds: Object.freeze([LEGAL_FIXTURE_PROFILE_IDS.artistYellow]),
      lifecycleStatus: 'COMPLETED',
      signedAt: '2026-03-01T12:40:00.000Z',
      permissions: sharedDocumentPermissions,
      locale: 'en',
      createdAt: '2026-03-01T12:00:00.000Z',
    }),
    Object.freeze({
      documentId: 'DOC-YELLOW-CTR-001',
      templateCode: 'CTR-001',
      category: 'CTR',
      templateVersionId: 'TV-CTR-001-1',
      versionLabel: '1.0',
      ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistYellow,
      signerProfileIds: Object.freeze([LEGAL_FIXTURE_PROFILE_IDS.artistYellow]),
      packageId: LEGAL_FIXTURE_PACKAGE_IDS.yellowPackage,
      lifecycleStatus: 'COMPLETED',
      signedAt: '2026-07-10T18:00:00.000Z',
      finalArtifactId: 'ART-YELLOW-CTR-001',
      permissions: sharedDocumentPermissions,
      locale: 'en',
      createdAt: '2026-07-08T12:00:00.000Z',
    }),
    Object.freeze({
      documentId: 'DOC-YELLOW-SPC-001',
      templateCode: 'SPC-001',
      category: 'SPC',
      templateVersionId: 'TV-SPC-001-1',
      versionLabel: '1.0',
      ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistYellow,
      signerProfileIds: Object.freeze([LEGAL_FIXTURE_PROFILE_IDS.artistYellow]),
      lifecycleStatus: 'COMPLETED',
      signedAt: '2026-03-05T18:00:00.000Z',
      finalArtifactId: 'ART-YELLOW-W9-001',
      permissions: sharedDocumentPermissions,
      locale: 'en',
      createdAt: '2026-03-05T17:00:00.000Z',
    }),
    Object.freeze({
      documentId: 'DOC-YELLOW-SPC-002',
      templateCode: 'SPC-002',
      category: 'SPC',
      templateVersionId: 'TV-SPC-002-1',
      versionLabel: '1.0',
      ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistYellow,
      signerProfileIds: Object.freeze([LEGAL_FIXTURE_PROFILE_IDS.artistYellow]),
      lifecycleStatus: 'COMPLETED',
      signedAt: '2026-03-10T18:00:00.000Z',
      expiresAt: '2026-08-10T00:00:00.000Z',
      finalArtifactId: 'ART-YELLOW-INS-001',
      permissions: sharedDocumentPermissions,
      locale: 'en',
      createdAt: '2026-03-10T17:00:00.000Z',
    }),
    Object.freeze({
      documentId: 'DOC-RED-LGL-001',
      templateCode: 'LGL-001',
      category: 'LGL',
      templateVersionId: 'TV-LGL-001-1',
      versionLabel: '2.1',
      ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.providerRed,
      signerProfileIds: Object.freeze([LEGAL_FIXTURE_PROFILE_IDS.providerRed]),
      lifecycleStatus: 'COMPLETED',
      signedAt: '2026-02-01T12:30:00.000Z',
      permissions: sharedDocumentPermissions,
      locale: 'en',
      createdAt: '2026-02-01T12:00:00.000Z',
    }),
    Object.freeze({
      documentId: 'DOC-RED-LGL-002',
      templateCode: 'LGL-002',
      category: 'LGL',
      templateVersionId: 'TV-LGL-002-1',
      versionLabel: '1.4',
      ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.providerRed,
      signerProfileIds: Object.freeze([LEGAL_FIXTURE_PROFILE_IDS.providerRed]),
      lifecycleStatus: 'COMPLETED',
      signedAt: '2026-02-01T12:35:00.000Z',
      permissions: sharedDocumentPermissions,
      locale: 'en',
      createdAt: '2026-02-01T12:00:00.000Z',
    }),
    Object.freeze({
      documentId: 'DOC-RED-CTR-001',
      templateCode: 'CTR-001',
      category: 'CTR',
      templateVersionId: 'TV-CTR-001-1',
      versionLabel: '1.0',
      ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.providerRed,
      signerProfileIds: Object.freeze([LEGAL_FIXTURE_PROFILE_IDS.providerRed]),
      lifecycleStatus: 'EXPIRED',
      signedAt: '2025-06-01T18:00:00.000Z',
      expiresAt: '2026-06-01T00:00:00.000Z',
      permissions: sharedDocumentPermissions,
      locale: 'en',
      createdAt: '2025-06-01T17:00:00.000Z',
    }),
    Object.freeze({
      documentId: 'DOC-RED-SPC-002',
      templateCode: 'SPC-002',
      category: 'SPC',
      templateVersionId: 'TV-SPC-002-1',
      versionLabel: '1.0',
      ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.providerRed,
      signerProfileIds: Object.freeze([LEGAL_FIXTURE_PROFILE_IDS.providerRed]),
      lifecycleStatus: 'EXPIRED',
      signedAt: '2025-05-01T18:00:00.000Z',
      expiresAt: '2026-05-15T00:00:00.000Z',
      permissions: sharedDocumentPermissions,
      locale: 'en',
      createdAt: '2025-05-01T17:00:00.000Z',
    }),
    Object.freeze({
      documentId: 'DOC-CLI-CTR-002',
      templateCode: 'CTR-002',
      category: 'CTR',
      templateVersionId: 'TV-CTR-002-1',
      versionLabel: '1.0',
      ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.client,
      signerProfileIds: Object.freeze([LEGAL_FIXTURE_PROFILE_IDS.client]),
      lifecycleStatus: 'COMPLETED',
      signedAt: '2026-04-05T18:00:00.000Z',
      finalArtifactId: 'ART-CLI-CTR-002',
      permissions: sharedDocumentPermissions,
      locale: 'en',
      createdAt: '2026-04-05T17:00:00.000Z',
    }),
    Object.freeze({
      documentId: 'DOC-CLI-LGL-001',
      templateCode: 'LGL-001',
      category: 'LGL',
      templateVersionId: 'TV-LGL-001-1',
      versionLabel: '2.1',
      ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.client,
      signerProfileIds: Object.freeze([LEGAL_FIXTURE_PROFILE_IDS.client]),
      lifecycleStatus: 'COMPLETED',
      signedAt: '2026-04-01T12:30:00.000Z',
      finalArtifactId: 'ART-CLI-LGL-001',
      permissions: sharedDocumentPermissions,
      locale: 'en',
      createdAt: '2026-04-01T12:00:00.000Z',
    }),
    Object.freeze({
      documentId: 'DOC-EXT-CTR-001',
      templateCode: 'CTR-001',
      category: 'CTR',
      templateVersionId: 'TV-CTR-001-1',
      versionLabel: '1.0',
      ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.externalSigner,
      signerProfileIds: Object.freeze([LEGAL_FIXTURE_PROFILE_IDS.externalSigner]),
      packageId: LEGAL_FIXTURE_PACKAGE_IDS.externalPackage,
      lifecycleStatus: 'IN_PROGRESS',
      permissions: sharedDocumentPermissions,
      locale: 'en',
      createdAt: '2026-07-15T12:00:00.000Z',
    }),
  ];
}

const packages: SignaturePackage[] = [
  Object.freeze({
    packageId: LEGAL_FIXTURE_PACKAGE_IDS.yellowPackage,
    packageCode: 'ONBOARD-ARTIST-2026',
    recipientProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistYellow,
    recipientEmail: artistYellowProfile.primaryEmail,
    recipientLegalName: artistYellowProfile.legalName,
    recipientRole: 'artist',
    createdByStaffId: STAFF_ID,
    signingStatus: 'WAITING_SIGNATURE',
    documentCount: 2,
    completedCount: 1,
    progressRatio: '0.50',
    items: Object.freeze([
      Object.freeze({
        itemOrder: 1,
        templateCode: 'CTR-001',
        documentId: 'DOC-YELLOW-CTR-001',
        itemStatus: 'signed',
        requiresCountersign: true,
      }),
      Object.freeze({
        itemOrder: 2,
        templateCode: 'SPC-002',
        documentId: 'DOC-YELLOW-SPC-002',
        itemStatus: 'pending',
        requiresCountersign: false,
      }),
    ]),
    signers: Object.freeze([
      Object.freeze({
        signerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistYellow,
        signerRole: 'artist',
        signerEmail: artistYellowProfile.primaryEmail,
        signOrder: 1,
      }),
    ]),
    priority: 'normal',
    expiresAt: '2026-07-22T21:00:00.000Z',
    deliveredAt: '2026-07-18T12:00:00.000Z',
  }),
  Object.freeze({
    packageId: LEGAL_FIXTURE_PACKAGE_IDS.externalPackage,
    packageCode: 'EXTERNAL-SIGN-2026',
    recipientProfileId: LEGAL_FIXTURE_PROFILE_IDS.externalSigner,
    recipientEmail: externalSignerProfile.primaryEmail,
    recipientLegalName: externalSignerProfile.legalName,
    recipientRole: 'external',
    createdByStaffId: STAFF_ID,
    signingStatus: 'DELIVERED',
    documentCount: 1,
    completedCount: 0,
    progressRatio: '0.00',
    items: Object.freeze([
      Object.freeze({
        itemOrder: 1,
        templateCode: 'CTR-001',
        documentId: 'DOC-EXT-CTR-001',
        itemStatus: 'in_progress',
        requiresCountersign: false,
      }),
    ]),
    signers: Object.freeze([
      Object.freeze({
        signerProfileId: LEGAL_FIXTURE_PROFILE_IDS.externalSigner,
        signerRole: 'external',
        signerEmail: externalSignerProfile.primaryEmail,
        signOrder: 1,
      }),
    ]),
    priority: 'normal',
    expiresAt: '2026-07-27T21:00:00.000Z',
    deliveredAt: '2026-07-15T12:00:00.000Z',
  }),
];

const signingSessions: SigningSession[] = [
  Object.freeze({
    sessionId: 'SES-EXT-001',
    packageId: LEGAL_FIXTURE_PACKAGE_IDS.externalPackage,
    signerProfileId: LEGAL_FIXTURE_PROFILE_IDS.externalSigner,
    authMode: 'token',
    tokenId: 'lab-stub-token-ref-only',
    status: 'active',
    wizardStep: 1,
    startedAt: '2026-07-15T12:05:00.000Z',
    locale: 'en',
    deviceClass: 'desktop',
    browserFamily: 'Chrome',
    ipHash: 'ip:hash:ext001',
    userAgentTrunc: 'Mozilla/5.0 lab stub',
  }),
];

const taxProfiles: TaxProfile[] = [
  Object.freeze({
    taxProfileId: 'TAX-ART-GREEN-001',
    ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistGreen,
    w9Status: 'approved',
    w9DocumentId: 'DOC-GREEN-SPC-001',
    w9ArtifactId: 'ART-GREEN-W9-001',
    tinLast4: '1234',
    taxClassification: 'individual',
    approvedAt: '2026-01-17T10:00:00.000Z',
    approvedByStaffId: STAFF_ID,
    updatedAt: NOW,
  }),
  Object.freeze({
    taxProfileId: 'TAX-ART-YELLOW-001',
    ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistYellow,
    w9Status: 'approved',
    w9DocumentId: 'DOC-YELLOW-SPC-001',
    w9ArtifactId: 'ART-YELLOW-W9-001',
    tinLast4: '5678',
    taxClassification: 'individual',
    approvedAt: '2026-03-06T10:00:00.000Z',
    approvedByStaffId: STAFF_ID,
    updatedAt: NOW,
  }),
  Object.freeze({
    taxProfileId: 'TAX-PRO-RED-001',
    ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.providerRed,
    w9Status: 'missing',
    rejectionReasonCode: 'not_submitted',
    updatedAt: NOW,
  }),
];

const complianceProfiles: ComplianceProfile[] = [
  Object.freeze({
    complianceProfileId: 'CMP-ART-GREEN-001',
    ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistGreen,
    aggregateCompliance: 'allowed',
    matrices: Object.freeze({
      private_event: Object.freeze([
        Object.freeze({ requirementCode: 'partner_agreement', state: 'fulfilled' }),
        Object.freeze({ requirementCode: 'w9', state: 'fulfilled' }),
        Object.freeze({ requirementCode: 'policy_bundle', state: 'fulfilled' }),
      ]),
      restaurant: Object.freeze([
        Object.freeze({ requirementCode: 'partner_agreement', state: 'fulfilled' }),
        Object.freeze({ requirementCode: 'insurance', state: 'fulfilled' }),
        Object.freeze({ requirementCode: 'policy_bundle', state: 'fulfilled' }),
      ]),
      corporate_event: Object.freeze([
        Object.freeze({ requirementCode: 'partner_agreement', state: 'fulfilled' }),
        Object.freeze({ requirementCode: 'insurance', state: 'fulfilled' }),
        Object.freeze({ requirementCode: 'w9', state: 'fulfilled' }),
      ]),
    }),
    evaluatedAt: NOW,
  }),
  Object.freeze({
    complianceProfileId: 'CMP-ART-YELLOW-001',
    ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistYellow,
    aggregateCompliance: 'warning',
    matrices: Object.freeze({
      private_event: Object.freeze([
        Object.freeze({ requirementCode: 'partner_agreement', state: 'fulfilled' }),
        Object.freeze({ requirementCode: 'w9', state: 'fulfilled' }),
      ]),
      corporate_event: Object.freeze([
        Object.freeze({
          requirementCode: 'insurance',
          state: 'pending',
          sourceDocumentId: 'DOC-YELLOW-SPC-002',
          expiresAt: '2026-08-10T00:00:00.000Z',
        }),
        Object.freeze({ requirementCode: 'partner_agreement', state: 'fulfilled' }),
      ]),
    }),
    evaluatedAt: NOW,
  }),
  Object.freeze({
    complianceProfileId: 'CMP-PRO-RED-001',
    ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.providerRed,
    aggregateCompliance: 'blocked',
    matrices: Object.freeze({
      private_event: Object.freeze([
        Object.freeze({ requirementCode: 'w9', state: 'blocking' }),
        Object.freeze({ requirementCode: 'anti_bypass', state: 'blocking' }),
      ]),
      corporate_event: Object.freeze([
        Object.freeze({ requirementCode: 'partner_agreement', state: 'blocking' }),
        Object.freeze({ requirementCode: 'insurance', state: 'blocking' }),
        Object.freeze({ requirementCode: 'w9', state: 'blocking' }),
        Object.freeze({ requirementCode: 'anti_bypass', state: 'blocking' }),
      ]),
    }),
    evaluatedAt: NOW,
  }),
  Object.freeze({
    complianceProfileId: 'CMP-CLI-001',
    ownerProfileId: LEGAL_FIXTURE_PROFILE_IDS.client,
    aggregateCompliance: 'allowed',
    matrices: Object.freeze({
      private_event: Object.freeze([
        Object.freeze({ requirementCode: 'service_agreement', state: 'fulfilled' }),
      ]),
    }),
    evaluatedAt: NOW,
  }),
];

const introductions: IntroductionRecord[] = [
  Object.freeze({
    introductionId: LEGAL_FIXTURE_INTRODUCTION_IDS.canonical,
    platformParty: 'Miami DJ Beat LLC',
    performerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistGreen,
    performerDisplayName: 'DJMago305',
    counterpartyType: 'restaurant',
    counterpartyName: 'Mojitos Calle 8',
    introductionDate: '2026-05-01T00:00:00.000Z',
    introductionSource: 'platform_match',
    introductionEvidence: 'lead-evt-2026-0501-mojitos',
    protectionStatus: 'active',
    protectionExpiresAt: '2028-05-01T00:00:00.000Z',
    createdBy: 'system',
  }),
];

const signatureRecords: SignatureRecord[] = [
  Object.freeze({
    signatureId: 'SIG-GREEN-001',
    sessionId: 'SES-GREEN-001',
    documentId: 'DOC-GREEN-CTR-001',
    templateVersionId: 'TV-CTR-001-1',
    signerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistGreen,
    signatureType: 'typed',
    signaturePayloadHash: 'sha256:green-ctr-001',
    typedText: 'Gerardo A Valle',
    recordedAt: '2026-01-15T18:00:00.000Z',
    locale: 'en',
  }),
  Object.freeze({
    signatureId: 'SIG-YELLOW-001',
    sessionId: 'SES-YELLOW-001',
    documentId: 'DOC-YELLOW-CTR-001',
    templateVersionId: 'TV-CTR-001-1',
    signerProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistYellow,
    signatureType: 'typed',
    signaturePayloadHash: 'sha256:yellow-ctr-001',
    typedText: 'DJ Nova Lab',
    recordedAt: '2026-07-10T18:00:00.000Z',
    locale: 'en',
  }),
  Object.freeze({
    signatureId: 'SIG-CLI-001',
    sessionId: 'SES-CLI-001',
    documentId: 'DOC-CLI-CTR-002',
    templateVersionId: 'TV-CTR-002-1',
    signerProfileId: LEGAL_FIXTURE_PROFILE_IDS.client,
    signatureType: 'typed',
    signaturePayloadHash: 'sha256:cli-ctr-002',
    typedText: 'Sunset Events LLC',
    recordedAt: '2026-04-05T18:00:00.000Z',
    locale: 'en',
  }),
  Object.freeze({
    signatureId: 'SIG-CLI-002',
    sessionId: 'SES-CLI-001',
    documentId: 'DOC-CLI-LGL-001',
    templateVersionId: 'TV-LGL-001-1',
    signerProfileId: LEGAL_FIXTURE_PROFILE_IDS.client,
    signatureType: 'checkbox',
    signaturePayloadHash: 'sha256:cli-lgl-001',
    recordedAt: '2026-04-01T12:30:00.000Z',
    locale: 'en',
  }),
];

const acceptanceRecords: AcceptanceRecord[] = [
  Object.freeze({
    acceptanceId: 'ACC-GREEN-LGL-001',
    documentId: 'DOC-GREEN-LGL-001',
    templateCode: 'LGL-001',
    templateVersionId: 'TV-LGL-001-1',
    acceptorProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistGreen,
    acceptanceMethod: 'checkbox',
    acceptedAt: '2026-01-10T12:30:00.000Z',
    ipHash: 'ip:hash:green-lgl-001',
  }),
  Object.freeze({
    acceptanceId: 'ACC-GREEN-LGL-002',
    documentId: 'DOC-GREEN-LGL-002',
    templateCode: 'LGL-002',
    templateVersionId: 'TV-LGL-002-1',
    acceptorProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistGreen,
    acceptanceMethod: 'checkbox',
    acceptedAt: '2026-01-10T12:35:00.000Z',
    ipHash: 'ip:hash:green-lgl-002',
  }),
  Object.freeze({
    acceptanceId: 'ACC-GREEN-LGL-003',
    documentId: 'DOC-GREEN-LGL-003',
    templateCode: 'LGL-003',
    templateVersionId: 'TV-LGL-003-1',
    acceptorProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistGreen,
    acceptanceMethod: 'checkbox',
    acceptedAt: '2026-01-10T12:40:00.000Z',
    ipHash: 'ip:hash:green-lgl-003',
  }),
  Object.freeze({
    acceptanceId: 'ACC-YELLOW-LGL-001',
    documentId: 'DOC-YELLOW-LGL-001',
    templateCode: 'LGL-001',
    templateVersionId: 'TV-LGL-001-1',
    acceptorProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistYellow,
    acceptanceMethod: 'checkbox',
    acceptedAt: '2026-03-01T12:30:00.000Z',
    ipHash: 'ip:hash:yellow-lgl-001',
  }),
  Object.freeze({
    acceptanceId: 'ACC-YELLOW-LGL-002',
    documentId: 'DOC-YELLOW-LGL-002',
    templateCode: 'LGL-002',
    templateVersionId: 'TV-LGL-002-1',
    acceptorProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistYellow,
    acceptanceMethod: 'checkbox',
    acceptedAt: '2026-03-01T12:35:00.000Z',
    ipHash: 'ip:hash:yellow-lgl-002',
  }),
  Object.freeze({
    acceptanceId: 'ACC-YELLOW-LGL-003',
    documentId: 'DOC-YELLOW-LGL-003',
    templateCode: 'LGL-003',
    templateVersionId: 'TV-LGL-003-1',
    acceptorProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistYellow,
    acceptanceMethod: 'checkbox',
    acceptedAt: '2026-03-01T12:40:00.000Z',
    ipHash: 'ip:hash:yellow-lgl-003',
  }),
  Object.freeze({
    acceptanceId: 'ACC-RED-LGL-001',
    documentId: 'DOC-RED-LGL-001',
    templateCode: 'LGL-001',
    templateVersionId: 'TV-LGL-001-1',
    acceptorProfileId: LEGAL_FIXTURE_PROFILE_IDS.providerRed,
    acceptanceMethod: 'checkbox',
    acceptedAt: '2026-02-01T12:30:00.000Z',
    ipHash: 'ip:hash:red-lgl-001',
  }),
  Object.freeze({
    acceptanceId: 'ACC-RED-LGL-002',
    documentId: 'DOC-RED-LGL-002',
    templateCode: 'LGL-002',
    templateVersionId: 'TV-LGL-002-1',
    acceptorProfileId: LEGAL_FIXTURE_PROFILE_IDS.providerRed,
    acceptanceMethod: 'checkbox',
    acceptedAt: '2026-02-01T12:35:00.000Z',
    ipHash: 'ip:hash:red-lgl-002',
  }),
  Object.freeze({
    acceptanceId: 'ACC-CLI-LGL-001',
    documentId: 'DOC-CLI-LGL-001',
    templateCode: 'LGL-001',
    templateVersionId: 'TV-LGL-001-1',
    acceptorProfileId: LEGAL_FIXTURE_PROFILE_IDS.client,
    acceptanceMethod: 'checkbox',
    acceptedAt: '2026-04-01T12:30:00.000Z',
    ipHash: 'ip:hash:cli-lgl-001',
  }),
];

const auditEvents: AuditEvent[] = [
  Object.freeze({
    auditId: 'AUD-GREEN-001',
    eventType: 'DOCUMENT_SIGNED',
    occurredAt: '2026-01-15T18:00:00.000Z',
    actorType: 'user',
    actorIdHash: 'usr:hash:green',
    legalProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistGreen,
    documentId: 'DOC-GREEN-CTR-001',
    payload: Object.freeze({ templateCode: 'CTR-001' }),
  }),
  Object.freeze({
    auditId: 'AUD-GREEN-002',
    eventType: 'POLICY_ACCEPTED',
    occurredAt: '2026-01-10T12:40:00.000Z',
    actorType: 'user',
    actorIdHash: 'usr:hash:green',
    legalProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistGreen,
    documentId: 'DOC-GREEN-LGL-003',
    payload: Object.freeze({ templateCode: 'LGL-003' }),
  }),
  Object.freeze({
    auditId: 'AUD-GREEN-003',
    eventType: 'INTRODUCTION_REGISTERED',
    occurredAt: '2026-05-01T00:00:00.000Z',
    actorType: 'system',
    actorIdHash: 'sys:hash:intro',
    legalProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistGreen,
    introductionId: LEGAL_FIXTURE_INTRODUCTION_IDS.canonical,
    payload: Object.freeze({
      counterpartyName: 'Mojitos Calle 8',
      performerDisplayName: 'DJMago305',
    }),
  }),
  Object.freeze({
    auditId: 'AUD-YELLOW-001',
    eventType: 'PACKAGE_SENT',
    occurredAt: '2026-07-18T12:00:00.000Z',
    actorType: 'staff',
    actorIdHash: 'stf:hash:001',
    legalProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistYellow,
    packageId: LEGAL_FIXTURE_PACKAGE_IDS.yellowPackage,
    payload: Object.freeze({ packageCode: 'ONBOARD-ARTIST-2026' }),
  }),
  Object.freeze({
    auditId: 'AUD-RED-001',
    eventType: 'COMPLIANCE_BLOCKED',
    occurredAt: '2026-07-19T08:00:00.000Z',
    actorType: 'system',
    actorIdHash: 'sys:hash:compliance',
    legalProfileId: LEGAL_FIXTURE_PROFILE_IDS.providerRed,
    payload: Object.freeze({ aggregateCompliance: 'blocked' }),
  }),
  Object.freeze({
    auditId: 'AUD-EXT-001',
    eventType: 'PACKAGE_DELIVERED',
    occurredAt: '2026-07-15T12:00:00.000Z',
    actorType: 'staff',
    actorIdHash: 'stf:hash:001',
    legalProfileId: LEGAL_FIXTURE_PROFILE_IDS.externalSigner,
    packageId: LEGAL_FIXTURE_PACKAGE_IDS.externalPackage,
    payload: Object.freeze({ packageCode: 'EXTERNAL-SIGN-2026' }),
  }),
];

const notifications: LegalNotification[] = [
  Object.freeze({
    notificationId: 'NTF-YELLOW-001',
    notificationType: 'signature_required',
    recipientProfileId: LEGAL_FIXTURE_PROFILE_IDS.artistYellow,
    recipientChannel: 'in_app',
    severity: 'warning',
    titleKey: 'legal.notification.signature_required.title',
    bodyKey: 'legal.notification.signature_required.body',
    relatedEntityType: 'package',
    relatedEntityId: LEGAL_FIXTURE_PACKAGE_IDS.yellowPackage,
    createdAt: '2026-07-18T12:05:00.000Z',
  }),
  Object.freeze({
    notificationId: 'NTF-RED-001',
    notificationType: 'w9_required',
    recipientProfileId: LEGAL_FIXTURE_PROFILE_IDS.providerRed,
    recipientChannel: 'in_app',
    severity: 'critical',
    titleKey: 'legal.notification.w9_required.title',
    bodyKey: 'legal.notification.w9_required.body',
    relatedEntityType: 'tax',
    relatedEntityId: 'TAX-PRO-RED-001',
    createdAt: '2026-07-19T08:00:00.000Z',
  }),
  Object.freeze({
    notificationId: 'NTF-RED-002',
    notificationType: 'insurance_expired',
    recipientProfileId: LEGAL_FIXTURE_PROFILE_IDS.providerRed,
    recipientChannel: 'in_app',
    severity: 'critical',
    titleKey: 'legal.notification.insurance_expired.title',
    bodyKey: 'legal.notification.insurance_expired.body',
    relatedEntityType: 'document',
    relatedEntityId: 'DOC-RED-SPC-002',
    createdAt: '2026-07-19T08:05:00.000Z',
  }),
];

function indexById<T extends { readonly [K in IdKey]: string }, IdKey extends string>(
  items: readonly T[],
  key: IdKey,
): Map<string, T> {
  return new Map(items.map((item) => [item[key], item]));
}

function serializeStoreState(state: InMemoryLegalStoreState): unknown {
  return Object.freeze({
    profiles: Object.freeze([...state.profiles.values()]),
    documents: Object.freeze([...state.documents.values()]),
    packages: Object.freeze([...state.packages.values()]),
    signingSessions: Object.freeze([...state.signingSessions.values()]),
    signatureRecords: Object.freeze([...state.signatureRecords.values()]),
    acceptanceRecords: Object.freeze([...state.acceptanceRecords.values()]),
    taxProfiles: Object.freeze([...state.taxProfiles.values()]),
    complianceProfiles: Object.freeze([...state.complianceProfiles.values()]),
    introductions: Object.freeze([...state.introductions.values()]),
    auditEvents: Object.freeze([...state.auditEvents]),
    notifications: Object.freeze([...state.notifications.values()]),
  });
}

export function createLegalFixtureSeedState(): InMemoryLegalStoreState {
  const profiles = [
    artistGreenProfile,
    artistYellowProfile,
    providerRedProfile,
    clientProfile,
    externalSignerProfile,
  ];
  const documents = createDocuments();

  return {
    profiles: indexById(profiles, 'legalProfileId'),
    documents: indexById(documents, 'documentId'),
    packages: indexById(packages, 'packageId'),
    signingSessions: indexById(signingSessions, 'sessionId'),
    signatureRecords: indexById(signatureRecords, 'signatureId'),
    acceptanceRecords: indexById(acceptanceRecords, 'acceptanceId'),
    taxProfiles: indexById(taxProfiles, 'taxProfileId'),
    complianceProfiles: indexById(complianceProfiles, 'complianceProfileId'),
    introductions: indexById(introductions, 'introductionId'),
    auditEvents: [...auditEvents],
    notifications: indexById(notifications, 'notificationId'),
  };
}

export function collectFixtureSeedPayloadForSecretScan(): unknown {
  return Object.freeze({
    constants: Object.freeze({
      LEGAL_FIXTURE_PROFILE_IDS,
      LEGAL_FIXTURE_PACKAGE_IDS,
      LEGAL_FIXTURE_INTRODUCTION_IDS,
      LEGAL_FIXTURE_EXPEDIENTE,
    }),
    seed: serializeStoreState(createLegalFixtureSeedState()),
  });
}
